---
# file: docker-compose.yml
version: '3.7'
services:

  postgres:
    image: postgres:latest
    container_name: djankiserv_postgres_${POSTGRES_PORT-5432}
    ports:
      - ${POSTGRES_PORT-5432}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./instances/postgres_${POSTGRES_PORT-5432}:/var/lib/postgresql
    restart: unless-stopped